[package]
name = "bix"
version = "0.1.0"
authors = ["Jeremy Schwartz <j.schwartz564@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
