[package]
name = "wc"
version = "0.1.0"
authors = ["Jeremy Schwartz <j.schwartz564@icloud.com>"]
edition = "2018"

[dependencies]
bix = { path = ".." }
structopt = "0.3"
tokio = { version = "0.2.16", features = ["rt-threaded"] }